server:
  port: 8106

spring:
  application:
    name: notification-service
  config:
    import[0]: optional:nacos:notification-service.yaml?group=DEFAULT_GROUP
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
