server:
  port: 8002

spring:
  application:
    name: admin-gateway
  main:
    web-application-type: reactive

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        file-extension: yaml
        import-check:
          enabled: false
