server:
  port: 8002

spring:
  application:
    name: admin-gateway
  config:
    import[0]: optional:nacos:admin-gateway.yaml?group=DEFAULT_GROUP
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        file-extension: yaml
