server:
  port: 8107

spring:
  application:
    name: risk-control-service
  config:
    import[0]: optional:nacos:risk-control-service.yaml?group=DEFAULT_GROUP
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
