server:
  port: 8102

spring:
  application:
    name: restaurant-service
  config:
    import[0]: optional:nacos:restaurant-service.yaml?group=DEFAULT_GROUP
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        import-check:
          enabled: true

# MinIO 配置
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: campus-review
