server:
  port: 8104

spring:
  application:
    name: interaction-service
  config:
    import[0]: optional:nacos:interaction-service.yaml?group=DEFAULT_GROUP
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ip: 127.0.0.1
      config:
        server-addr: localhost:8848
        file-extension: yaml


