server:
  port: 8104

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      config:
        enabled: false
      discovery:
        enabled: true
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
  application:
    name: interaction-service
  datasource:
    url: jdbc:h2:mem:interactiondb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
