
server:
  port: 8108

spring:
  application:
    name: admin-service
  config:
    import[0]: optional:nacos:admin-service.yaml?group=DEFAULT_GROUP
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
